### ISSUE TITLE
Offer node-zopfli-es as ES6 module

### ISSUE THREAD

**Issue by dilyanpalauzov** [jaeh/node-zopfli-es#6]
I want to create an "index.html" file with rollup, which contains a script type=module and script nomodule tags. Per rollup/rollup#3536 rollup cannot call node-zopfli-es once the ES6 and ES5 outputs are ready. So I am trying to switch to rollup API : rollup.rollup().write(). In package.json I have "type":"module" and in the file with rollup.rollup(…).write(…) I insert `import {gzipSync} from 'node-zopfli-es'` as I had it in the rollup.config.js` file.

Node 14 says `node-zopfli-es is expected to be in CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default exports`.

* Add module to package.json and allow the plugin to be loaded as ES6 module.

**Comment by jaeh** [comment]
at the moment, this library is pure commonjs,
there is no ecmascript module functionality at all.

also
`CommonJS modules can be imported by importing the default exports.`

means you should be able to

```
import zopfli from 'node-zopfli-es'

const zipped = zopfli.gzipSync(data)
```

**Comment by dilyanpalauzov** [comment]
I would like to use the syntax `import {gzipSync} from 'node-zopfli-es'`.

https://github.com/TrySound/rollup-plugin-terser/commit/820201db3db274ab074f47f988bcf3a0bc53ad1f provides an example how the wrapping into ES6 can be done.

**Comment by jaeh** [comment]
at one point in the future i might rewrite this library in mjs,
until then, there is no benefit in doing anything, on the contrary, it would be misleading,
let me explain.

this library is written in commonjs, which, by default, imports the whole module, regardless if you use require or import to load it, and regardless of what you load. that's because require can use dynamic strings and load dependencies at runtime.

ecmascript modules on the other hand only import what you imported plus dependent functions,
and nothing else, making your program a bit smaller and faster.

afaik this error message is thrown within rollup, which means rollup decided that this is the correct way to import commonjs files into rollup bundles.

it follows that `import zopfli from 'node-zopfli-es'` is the correct way to import commonjs into ecmascript modules, at least in rollup, because it makes this difference between mjs and cjs clear.

```
import zopfli from 'node-zopfli-es'
const { gzipSync } = zopfli
```
is the tersest way to use the gzipSync function without the zopfli object.
